# Site settings
title: Re9ulus Blog
header-img: img/home-bg.jpg
email: re9ulusV@gmail.com
description: "IT, programming, data science"
baseurl: ""
# url: "http://yourdomain.com"
twitter_username: re9ulusV
github_username:  re9ulus
# facebook_username:  none

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
highlighter: rouge #pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
input: GFM

