# Site settings
title: Re9ulus Blog
header-img: img/home-bg.jpg
email: re9ulusV@gmail.com
description: "IT, programming, data science"
baseurl: ""
# url: "http://yourdomain.com"
twitter_username: re9ulusV
github_username:  re9ulus
# facebook_username:  none

# Build settings
markdown: kramdown
highlighter: rouge #pygments
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate]

kramdown:
    input: GFM
    syntax_highlighter: rouge
