# Site settings
title: Angeldars Blog
header-img: img/home-bg.jpg
email: angeldaren@gmail.com
description: "IT, programming, data science"
baseurl: ""
url: "http://yourdomain.com"
# twitter_username: angeldaren
github_username:  angeldar
# facebook_username:  none

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
